[package]
name = "server"
version = "0.1.0"
authors = ["Wojciech Smo≈Çka <sm.wojciech@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web ="2.*"
actix-rt = "1.0.0"